version: "3.3"

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile.app
    ports:
        - 8000:8000
        - 8081:8081
    # env_file:
    #   - .app.env
    # environment:
    # #   SOME_VAR: SOME_VAL
    networks:
        - default
    volumes:
        - ./:/app

  db:
    image: mariadb:latest
    env_file: 
        - .db.env
    ports:
        - 3306:3306
    volumes:
        - ./db:/docker-entrypoint-initdb.d
        - persistent:/var/lib/mysql
    networks:
        - default

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - 8082:80
      environment:
          PMA_HOST: db
      env_file: 
          - .db.env
      networks:
          - default 
volumes:
  persistent:
